### ISSUE TITLE
how to access my home network from outside

### ISSUE THREAD

**Issue by ghost** [alext-mkrs/edison-mon-sys#1]
https://communities.intel.com/thread/96445?start=0&tstart=0

To solved this error I need solution that's with your help: 

root@neuberfran:~# opkg install perl-CPAN
Unknown package 'perl-CPAN'.
Collected errors:
- opkg_install_cmd: Cannot install package perl-CPAN.

I need CPAN to include module (Hostname) in perl

**Comment by alext-mkrs** [comment]
This repo has nothing to do with your question. If anything, more appropriate one would be meta-alext-edison.

There's no CPAN package in my repo. Per the forum thread you've referenced, you need to install a package called perl-module-sys-hostname, which is available in the repo.

**Comment by ghost** [comment]
http://cgit.openembedded.org/openembedded/tree/recipes/ddclient/ddclient_3.6.3.bb
